# Generated by Django 2.2.5 on 2020-06-28 08:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
        ('prise_en_charge', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='mr',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='mr_mrs_zone',
            field=models.ForeignKey(max_length=64, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prise_charge_zonem', to='base.Zone'),
        ),
        migrations.AddField(
            model_name='document',
            name='mrs',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
