# Generated by Django 2.2.5 on 2020-06-28 08:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
        ('prise_en_charge', '0002_auto_20200628_1005'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='mr_mrs_zone',
        ),
        migrations.AddField(
            model_name='document',
            name='mr_mrs_quarter',
            field=models.ForeignKey(max_length=64, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prise_charge_res_quarter', to='base.Quarter'),
        ),
    ]
