# Generated by Django 2.2.5 on 2020-06-28 05:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
        ('vente_parcelle', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='amount',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='buyer',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='buyer_father',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='buyer_mother',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='buyer_residence_quarter',
            field=models.ForeignKey(max_length=64, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vente_residenceb', to='base.Quarter'),
        ),
        migrations.AddField(
            model_name='document',
            name='buyer_zone',
            field=models.ForeignKey(max_length=64, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vente_zoneb', to='base.Zone'),
        ),
    ]
