# Generated by Django 2.2.5 on 2020-06-28 06:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
        ('vente_parcelle', '0002_auto_20200628_0746'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='buyer_commune',
            field=models.ForeignKey(max_length=64, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vente_communeb', to='base.Commune'),
        ),
    ]
