# Generated by Django 2.2.5 on 2020-06-28 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vente_parcelle', '0005_remove_document_buyer_residence_quarter'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='cellule',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
