# Generated by Django 3.0 on 2020-06-27 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Notoriete', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='comparant_colline_naiisance',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
