# Generated by Django 3.0 on 2020-06-27 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Notoriete', '0002_document_comparant_colline_naiisance'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='comparant_colline_naiisance',
            new_name='comparant_colline_naissance',
        ),
        migrations.AddField(
            model_name='document',
            name='jour',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='document',
            name='mois',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
