# Generated by Django 3.0 on 2020-06-27 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Marriage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='jour',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='document',
            name='mois',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='document',
            name='year',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='document',
            name='nationalite_epouse',
            field=models.CharField(default='Burundaise', max_length=100),
        ),
    ]
