# Generated by Django 2.2.5 on 2020-06-30 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
        ('cession_parcelle', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='beneficiary',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='beneficiary_residence_zone',
            field=models.ForeignKey(max_length=64, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cession_res_zone', to='base.Zone'),
        ),
        migrations.AddField(
            model_name='document',
            name='beneficiary_zone',
            field=models.ForeignKey(max_length=64, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cession_zonee', to='base.Zone'),
        ),
        migrations.AddField(
            model_name='document',
            name='mrs',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='realestate_quarter',
            field=models.ForeignKey(max_length=64, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cession_quarterr', to='base.Quarter'),
        ),
    ]
