# Generated by Django 2.2.5 on 2020-06-30 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
        ('cession_parcelle', '0002_auto_20200630_1602'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='beneficiary_residence_quarter',
            field=models.ForeignKey(max_length=64, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cession_res_qu', to='base.Quarter'),
        ),
    ]
