# Generated by Django 2.2.5 on 2020-06-30 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cession_parcelle', '0003_document_beneficiary_residence_quarter'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='ben_eyewitness1',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='ben_eyewitness2',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='giv_eyewitness1',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='giv_eyewitness2',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
