# Generated by Django 2.2.5 on 2020-06-27 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reconnaisance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='association',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
