# Generated by Django 2.2.5 on 2020-06-27 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reconnaisance', '0002_document_association'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='start_year',
            field=models.CharField(max_length=4, null=True),
        ),
    ]
