# Generated by Django 2.2.5 on 2020-06-27 17:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Commune',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('ecocash', models.CharField(max_length=64, null=True)),
                ('lumicash', models.CharField(max_length=64, null=True)),
                ('bcb', models.CharField(max_length=64, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ModelDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.CharField(max_length=64)),
                ('is_valid', models.BooleanField(null=True)),
                ('place_level', models.IntegerField(choices=[(1, 'Pays'), (2, 'Province'), (3, 'Commune'), (4, 'Quarter'), (5, 'Zone')])),
                ('user_level', models.IntegerField(choices=[(1, 'Chef'), (2, 'Secretaire')])),
                ('place_name', models.CharField(max_length=64)),
                ('document_id', models.IntegerField()),
                ('priority', models.IntegerField(choices=[(1, 'Normal'), (2, 'Elevée')])),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('H', 'Homme'), ('F', 'Femme')], max_length=64)),
                ('nationnalite', models.CharField(max_length=64)),
                ('address', models.CharField(max_length=64)),
                ('CNI', models.CharField(blank=True, max_length=64, null=True)),
                ('father', models.CharField(blank=True, max_length=64, null=True)),
                ('mother', models.CharField(blank=True, max_length=64, null=True)),
                ('birthdate', models.DateField()),
                ('is_married', models.BooleanField(blank=True, default=False)),
                ('cni_recto', models.ImageField(blank=True, null=True, upload_to='cnis/')),
                ('cni_verso', models.ImageField(blank=True, null=True, upload_to='cnis/')),
                ('job', models.CharField(max_length=64, null=True)),
                ('prefix', models.CharField(max_length=12, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('ecocash', models.CharField(max_length=64, null=True)),
                ('lumicash', models.CharField(max_length=64, null=True)),
                ('bcb', models.CharField(max_length=64, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Quarter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('ecocash', models.CharField(max_length=64, null=True)),
                ('lumicash', models.CharField(max_length=64, null=True)),
                ('bcb', models.CharField(max_length=64, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UsedSN',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_transaction', models.CharField(max_length=64)),
                ('name_transaction', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('ecocash', models.CharField(max_length=64, null=True)),
                ('lumicash', models.CharField(max_length=64, null=True)),
                ('bcb', models.CharField(max_length=64, null=True)),
                ('commune', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Commune')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ZonePersonnel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_level', models.IntegerField(choices=[(1, 'Chef'), (2, 'Secretaire')])),
                ('sdate', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_valid', models.BooleanField(default=True)),
                ('edate', models.DateTimeField(blank=True, null=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Profile')),
                ('zone', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.Zone')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='QuarterPersonnel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_level', models.IntegerField(choices=[(1, 'Chef'), (2, 'Secretaire')])),
                ('sdate', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_valid', models.BooleanField(default=True)),
                ('edate', models.DateTimeField(blank=True, null=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Profile')),
                ('quarter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.Quarter')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='quarter',
            name='zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Zone'),
        ),
        migrations.CreateModel(
            name='ProvincePersonnel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_level', models.IntegerField(choices=[(1, 'Chef'), (2, 'Secretaire')])),
                ('sdate', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_valid', models.BooleanField(default=True)),
                ('edate', models.DateTimeField(blank=True, null=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Profile')),
                ('province', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.Province')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='profile',
            name='quarter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_quarter', to='base.Quarter'),
        ),
        migrations.AddField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='PaymentZone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_payement', models.CharField(choices=[('ecocash', 'Ecocash'), ('lumicash', 'Lumicash'), ('bcb', 'BCB')], max_length=64)),
                ('id_transaction', models.CharField(max_length=64)),
                ('bordereau', models.ImageField(blank=True, null=True, upload_to='bordereaux/')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_valid', models.BooleanField(null=True)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zone', to='base.Zone')),
            ],
            options={
                'verbose_name_plural': 'Payments per Zone',
            },
        ),
        migrations.CreateModel(
            name='PaymentQuarter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_payement', models.CharField(choices=[('ecocash', 'Ecocash'), ('lumicash', 'Lumicash'), ('bcb', 'BCB')], max_length=64)),
                ('id_transaction', models.CharField(max_length=64)),
                ('bordereau', models.ImageField(blank=True, null=True, upload_to='bordereaux/')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_valid', models.BooleanField(null=True)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quarter', to='base.Quarter')),
            ],
            options={
                'verbose_name_plural': 'Payments per Quarter',
            },
        ),
        migrations.CreateModel(
            name='PaymentProvince',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_payement', models.CharField(choices=[('ecocash', 'Ecocash'), ('lumicash', 'Lumicash'), ('bcb', 'BCB')], max_length=64)),
                ('id_transaction', models.CharField(max_length=64)),
                ('bordereau', models.ImageField(blank=True, null=True, upload_to='bordereaux/')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_valid', models.BooleanField(null=True)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='province', to='base.Province')),
            ],
            options={
                'verbose_name_plural': 'Payments per Province',
            },
        ),
        migrations.CreateModel(
            name='PaymentCommune',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_payement', models.CharField(choices=[('ecocash', 'Ecocash'), ('lumicash', 'Lumicash'), ('bcb', 'BCB')], max_length=64)),
                ('id_transaction', models.CharField(max_length=64)),
                ('bordereau', models.ImageField(blank=True, null=True, upload_to='bordereaux/')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_valid', models.BooleanField(null=True)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commune', to='base.Commune')),
            ],
            options={
                'verbose_name_plural': 'Payments per Commune',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=128)),
                ('seen', models.BooleanField(default=False)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CommunePersonnel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_level', models.IntegerField(choices=[(1, 'Chef'), (2, 'Secretaire')])),
                ('sdate', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_valid', models.BooleanField(default=True)),
                ('edate', models.DateTimeField(blank=True, null=True)),
                ('commune', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.Commune')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Profile')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='commune',
            name='province',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Province'),
        ),
    ]
