# Generated by Django 3.0 on 2020-06-27 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20200626_0802'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='colline_natal',
            field=models.CharField(default=1, max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='commune_natal',
            field=models.CharField(default=1, max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='province_natal',
            field=models.CharField(default=1, max_length=64),
            preserve_default=False,
        ),
    ]
