# Generated by Django 3.0 on 2020-06-28 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CompositionFamilliale', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Children',
            new_name='Child',
        ),
    ]
